import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ParentNav from "@/defaults/home-nav/ParentNav";
import ParentFooter from "@/defaults/home-footer/ParentFooter";
import AosWrapper from "@/defaults/aos-wrapper/AosWrapper";
import NextTopLoader from "nextjs-toploader";
import Context from "@/defaults/context/Context";
import ThemeProvider from "@/components/theme-provider";
import { Toaster } from "sonner";
import { Suspense } from "react"; // 1. Imported Suspense

import MetaPixel from "@/components/MetaPixel"; // 2. Imported MetaPixel
import GoogleAnalytics from "@/components/GoogleAnalytics";
// import ChatbotComponent from "@/defaults/ChatbotComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Elham Books",
  description: "Generated by Elham Books",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="application-name" content="PWA App" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="PWA App" />
        <meta name="description" content="Best PWA App in the world" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="msapplication-config" content="/icons/browserconfig.xml" />
        <meta name="msapplication-TileColor" content="#2B5797" />
        <meta name="msapplication-tap-highlight" content="no" />
        <meta name="theme-color" content="#000000" />

        <link rel="apple-touch-icon" href="/logo.png" />
        <link rel="apple-touch-icon" sizes="152x152" href="/logo.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/logo.png" />
        <link rel="apple-touch-icon" sizes="167x167" href="/logo.png" />

        <link rel="icon" type="image/png" sizes="32x32" href="/logo.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/logo.png" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="mask-icon" href="/logo.png" color="#5bbad5" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" />

        <meta name="twitter:card" content="summary" />
        <meta name="twitter:url" content="https://next-js-full-stack-e-comers.vercel.app" />
        <meta name="twitter:title" content="PWA App" />
        <meta name="twitter:description" content="Best PWA App in the world" />
        <meta name="twitter:image" content="https://next-js-full-stack-e-comers.vercel.app/logo.png" />
        <meta name="twitter:creator" content="@DavidWShadow" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="PWA App" />
        <meta property="og:description" content="Best PWA App in the world" />
        <meta property="og:site_name" content="PWA App" />
        <meta property="og:url" content="https://next-js-full-stack-e-comers.vercel.app" />
        <meta property="og:image" content="https://next-js-full-stack-e-comers.vercel.app/logo.png" />

        <link rel='apple-touch-startup-image' href='/logo.png' sizes='2048x2732' />
        <link rel='apple-touch-startup-image' href='/logo.png' sizes='1668x2224' />
        <link rel='apple-touch-startup-image' href='/logo.png' sizes='1536x2048' />
        <link rel='apple-touch-startup-image' href='/logo.png' sizes='1125x2436' />
        <link rel='apple-touch-startup-image' href='/logo.png' sizes='1242x2208' />
        <link rel='apple-touch-startup-image' href='/logo.png' sizes='750x1334' />
        <link rel='apple-touch-startup-image' href='/logo.png' sizes='640x1136' />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <AosWrapper>
            <NextTopLoader
              color="#FFFF00"
              showSpinner={true}
              height={3}
              zIndex={99999999999}
            />
            <Context>
              {/* 3. Inserted MetaPixel wrapper here */}
              <Suspense fallback={null}>
                <MetaPixel />
                <GoogleAnalytics />
              </Suspense>

              <Toaster className="z-[999999]" />
              <ParentNav />
              {/* <ChatbotComponent /> */}
              {children}
              <ParentFooter />
            </Context>
          </AosWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}